config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  root to: 'questions#index'
  resources :questions
  resource :session, only: %i[new create destroy]
  resources :users, only: %i[new create edit update destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/name.rb
class Name < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  before_save :downcase_nick
  has_secure_password

  validates :email, presence: true, uniqueness: true
  def downcase_nick
    nickname.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_quest, only: %i[edit show update destroy]
  def create
    @question = Question.create(quest_params)

    redirect_to question_path(@question), notice: 'Новый вопрос создан'
  end

  def edit; end

  def show; end

  def index
    @question = Question.new
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def update
    @question.update(quest_params)
    redirect_to question_path(@question), notice: 'Сохранили вопрос'
  end

  def destroy
    @question.destroy

    redirect_to questions_path, notice: 'Удалили вопрос'
  end

  private

  def set_quest
    @question = Question.find(params[:id])
  end

  def quest_params
    params.require(:question).permit(:body, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user_params = params.require(:session)
    user = User.find_by(email: user_params[:emai])&.authenticate(session(user_params[:password]))

    if user.present?
      session[:user_id] = user.id

      redirect_to root_path, notice: 'Вы вошли на сайт'
    else
      flash[:alert] = 'Неправильный пароль'

      redirect_to :new
    end
  end

  def destroy
    session.delete(:user_id)

    redirect_to root_path, notice: 'Вы вышли из аккаунта'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update destroy]
  def new
    @user = User.new
  end

  def create
    @user = User.new(params_user)
    if @user.save
      redirect_to root_path, notice: 'Вы зарегистрировались'
    else
      flash.now[:alert] = 'Вы неправильно заполнили поля формы регистрации'
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(params_user)
      redirect_to root_path, notice: 'Данные пользователя обновлены'
    else
      flash.now[:alert] = 'При попытке сохранить пользователя возникли ошибки'
      render :edit
    end
  end

  def destroy
    @user.destroy

    session.delete(:user_id)

    redirect_to root_path, notice: 'Пользователь удален'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def params_user
    params.require(:user).permit(:name, :nickname, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def inclination(count, one, few, many)
    return many if (count % 100).between?(11, 14)

    case count % 10
    when 1 then one
    when 2..4 then few
    else
      many
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AskMe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
      <div class='wrapper'>
        <% if flash[:notice].present? %> 
    <p class="mb mt message message-notice"><%= flash[:notice] %></p>
    <% end %>
        <div class="navbar">
        <p class="title-sm text-bold"><%= link_to "Ask_me!", root_path %></p>
        
        <div>
          <% if current_user.present? %> 
          <%= content_tag 'span',"@#{current_user.nickname}" %> 
          <%= button_to "Выйти", session_path, method: :delete %>
          <% else %>
          <%= link_to "Регистрация", new_user_path , class: "button button-yelow" %> 
          <%= link_to "Вход", new_session_path, class: "button button-yelow" %>
          <% end %>
        </div>
      </div>
    </div>
    <%= yield %>
    
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with model: question do |form| %> 
   <p><%= form.label :body, "Текст вопроса" %></p> 
   <p><%= form.text_area :body ,rows: 5,class: "form-text-area" %></p>
   <p class="mt"> <%= form.label :user_id, "Id:" %></p> 
   <p><%= form.text_field :user_id, class: "form-text-field" %></p>
   <p class="mt"><%= form.submit  "Сохранить", class: 'button button-main'%></p>
   
   <% end %> 
   

app/views/questions/_question.html.erb
<div class='mb-sm'><p><%= question.body %></p></div>
<div class="text-sm question footer">
  <div class="text-grey">
    <%= l(question.created_at, format: :short) %></div>
<div class="text-right"><%= link_to fa_icon('trash-o'), question_path(question), method: :delete, title: "Удалить вопрос" %>
<%= link_to fa_icon('pencil'), edit_question_path(question), title: "Изменить вопрос" %></div></div>

app/views/questions/edit.html.erb
<div class="container">
   <h2 class="title-lg mb">Редактирование вопроса<%= @question.body %></h2>
<%= render "form", question: @question %>
</div>
   

app/views/questions/index.html.erb
<div class="container"><h2 class="title-lg mb">Все вопросы</h2>

<p><% @questions.each do |quest| %> 
 <div class="mt-sm container"><p><%= link_to "Вопрос #{quest.id}", question_path(quest) %></p></div>
    <% end %>
  </p>
  <p><%= @questions.count %></p>
  <p><%= inclination(@questions.count, "вопрос","вопроса","вопросов") %></p>
  <p><%= link_to "Создать новый вопрос", new_question_path , class: 'button button-main' %></p>
<%=render @questions %></div>
<%= render "form", question: @question %>
  

app/views/questions/new.html.erb
 <div class="container">
  <h1 class="title-lg mb">Новый вопрос</h1>
  <%= render "form",question: @question %>
 </div>
   

app/views/questions/show.html.erb
<div class="container">
 
<h2 class="title-lg mb">Вопрос <%= @question.id %></h2>
<p class="mt-lg"><%=render "question",question: @question %></p>
<p><%= link_to "Все вопросы", questions_path %></p>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div class="container">
  <h2 class="title">Редактирование пользователя</h2> 
   <%= if @user.errors.any? %> 
  <div class="mt">
  <%= @user.errors.full_messages.each do |message| %> 
  <p class="mb-sm text-red"><% message %></p>
    <% end %>
  </div>
  <% end %>
  <div class="mt">
    <%= form_with model: @user, data: { turbo: false} do |form| %>
    <p><%= form.label :name, "Ваше имя" %></p>
    <p><%= form.text_field :name, class: "form-text-field" %></p>

    <p><%= form.label :nickname, "Ваше имя" %></p>
    <p><%= form.text_field :nikname, class: "form-text-field" %></p> 

    <p><%= form.label :email, "Ваше имя" %></p>
    <p><%= form.text_field :email, class: "form-text-field" %></p>

    <p><%= form.label :password %></p>
    <p><%= form.password_field :password, class: "form-text-field" %></p>

    <p><%= form.label :password_confirmation %></p>
    <p><%= form.password_field :password_confirmation, class: "form-text-field" %></p>

    <p><%= form.submit "Зарегистрироваться",class: "button button-main" %></p>
    <% end %>
  </div>
  <div class="mt-lg">
    <%= button_to "Удалить профиль", user_path(@user) , 
    method: :delete,
    form: { data: { turbo_confirm: "Вы точно хотите удалить свой профиль?" }},
    class: "text-red text-sm" %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <h2 class="title">Присоединяйся и спрашивай</h2>

  <% if @user.errors.any? %> 
  <div class="mt">
  <%= @user.errors.full_messages.each do |message| %> 
  <p class="mb-sm text-red"><% message %></p>
    <% end %>
  </div>
  <% end %>
  
    
    <p><%= form_with model: @user , data: { turbo: false } do |form| %></p>

    <p><%= form.label :name, "Ваше имя" %></p>
    <p><%= form.text_field :name, class: "form-text-field" %></p>

    <p class="mt"><%= form.label :nickname, "Ник на сайте" %></p>
    <p><%= form.text_field :nikname, class: "form-text-field" %></p> 

    <p class="mt"><%= form.label :email %></p>
    <p><%= form.text_field :email, class: "form-text-field" %></p>

    <p><%= form.label :password %></p>
    <p><%= form.password_field :password, class: "form-text-field" %></p>

    <p><%= form.label :password_confirmation %></p>
    <p><%= form.password_field :password_confirmation, class: "form-text-field" %></p>

    <p class="mt lg"><%= form.submit "Зарегистрироваться",class: "button button-main" %></p>

  <% end %>
  </div>
</div>